### DISCUSSION TITLE
FIle Format Error

### DISCUSSION THREAD

**Discussion by noor-muradi** [immauss/openvas#243] [General]
Hi team,
FIrst, I want to thank you guys for putting effort for this amazing job you guys have done, I trying to deploy the openvas on my K8s cluster, I am using version container image with tag `21.04.09`, but I am getting below `file format error` and the container crushes.

```
Setting up contianer filesystem
cp: cannot stat '/usr/local/var/lib/*': No such file or directory
cp: cannot stat '/var/lib/gvm/*': No such file or directory
cp: cannot stat '/var/lib/openvas/*': No such file or directory
Using default gvm logging config
Using default gvm logging config
Using default openvas logging config
Choosing container start method from:

Starting gvmd & openvas in a single container !!
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Creating postgresql.conf and pg_hba.conf
Starting PostgreSQL...
waiting for server to start....2024-01-16 05:50:37.897 UTC [87] LOG:  redirecting log output to logging collector process
2024-01-16 05:50:37.897 UTC [87] HINT:  Future log output will appear in directory "/data/var-log/postgresql".
 done
server started
pg exit with 0 .
Checking for existing DB
Loading Default Database
Running first start configuration...
Generating certs...
Generated private key in /tmp/tmp.L2ttCr4Por/cakey.pem.
Generated self signed certificate in /tmp/tmp.L2ttCr4Por/cacert.pem.
Installed private key to /var/lib/gvm/private/CA/cakey.pem.
Installed certificate to /var/lib/gvm/CA/cacert.pem.
Generated private key in /tmp/tmp.L2ttCr4Por/serverkey.pem.
Generated certificate request in /tmp/tmp.L2ttCr4Por/serverrequest.pem.
Signed certificate request in /tmp/tmp.L2ttCr4Por/serverrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.L2ttCr4Por/servercert.pem
Installed private key to /var/lib/gvm/private/CA/serverkey.pem.
Installed certificate to /var/lib/gvm/CA/servercert.pem.
Generated private key in /tmp/tmp.L2ttCr4Por/clientkey.pem.
Generated certificate request in /tmp/tmp.L2ttCr4Por/clientrequest.pem.
Signed certificate request in /tmp/tmp.L2ttCr4Por/clientrequest.pem with CA certificate in /var/lib/gvm/CA/cacert.pem to generate certificate in /tmp/tmp.L2ttCr4Por/clientcert.pem
Installed private key to /var/lib/gvm/private/CA/clientkey.pem.
Installed certificate to /var/lib/gvm/CA/clientcert.pem.
Removing temporary directory /tmp/tmp.L2ttCr4Por.
########################################
Creating a base DB from /usr/lib/base-db.xz
base data from:
Sun Jul 24 21:37:48 UTC 2022
########################################
xzcat: /usr/lib/base.sql.xz: File format not recognized

```

**Comment by immauss** [comment]
Any particular reason you are using such an old version? 
That version not even available on docker hub anymore... 

If you could, please try either the "latest" tag or 22.4.39. 

Thank you,
-Scott

**Reply by noor-muradi** [reply]
Thanks for the reply,
Actually I always go one version behind the latest or use the stable version if available because of stability, I tried the version `22.4.38` but the container crushes with below errors, then I wanted to try an old version, and see if that works, which didn't.

```
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032: lockfile_lock: lock 'gvm-create-functions'
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql: SELECT EXISTS (SELECT * FROM information_schema.tables               WHERE table_catalog = 'gvmd'               AND table_schema = 'public'               AND table_name = 'meta')        ::integer;
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql_x end (SELECT EXISTS (SELECT * FROM information_schema.tables               WHERE table_catalog = '%s'               AND table_schema = 'public'               AND table_name = 'meta')        ::integer;)
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql: SELECT value FROM public.meta WHERE name = 'database_version' LIMIT 1;
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql_x end (SELECT value FROM %s.meta WHERE name = 'database_version' LIMIT 1;)
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032: lockfile_unlock: unlock '/var/lib/gvm/gvmd/gvm-create-functions'
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql: BEGIN;
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql: SELECT id FROM users WHERE name = 'admin' ORDER BY id DESC;
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql_x end (SELECT id FROM %ss WHERE name = '%s' ORDER BY id DESC;)
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql: SELECT uuid FROM users WHERE id = 1;
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql_x end (SELECT uuid FROM users WHERE id = %llu;)

(gvmd:1032): libgvm base-WARNING **: 11:55:01.423: error opening '/etc/gvm/pwpolicy.conf': No such file or directory
md manage:WARNING:2024-01-16 11h55.01 utc:1032: new password for 'admin' rejected: Password policy checking failed (internal error)
New password rejected: Password policy checking failed (internal error)
md manage:  DEBUG:2024-01-16 11h55.01 utc:1032:    sql: ROLLBACK;

```
And this is the K8s deployment manifest that I am using:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vas
  name: openvas
  namespace: vas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vas
  strategy: {}
  template:
    metadata:
      labels:
        app: vas
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - public-ng #node group name
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vas-pvc
      containers:
      - image: immauss/openvas:22.4.38
        name: openvas
        ports:
        - containerPort: 9392
        env:
          - name: PASSWORD
            value: "deducted"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 256m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vas
  name: vas
  namespace: vas
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9392
  selector:
    app: vas
```
