### ISSUE TITLE
NVT Sync error on startup, container doesn't start

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#18]
Using latest version (as of today 2020-10-31) with compose
```
openvas:
  container_name: openvas
  environment:
   - PASSWORD=xxx
   - RELAYHOST=xxx.com
  #hostname: openvas.${hostname}
  image: immauss/openvas
  labels:
   - com.centurylinklabs.watchtower.enable=true
  ports:
   - 8083:9392
  restart: always
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
   - /opt/docker/openvas:/data
```
container restarts with error message from the logs:
```
Setup / Fix the /usr/local/var/run
10:C 31 Oct 12:16:16.494 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
10:C 31 Oct 12:16:16.494 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=10, just started
10:C 31 Oct 12:16:16.494 # Configuration loaded
Wait for redis socket to be created...
Testing redis status...
Redis ready.
Starting PostgreSQL...
Removed stale pid file.
Fixing sync script options ...
Updating NVTs...
<28>Oct 31 12:16:19 greenbone-nvt-sync: The log facility is not working as expected. All messages will be written to the standard error stream.
<28>Oct 31 12:16:19 greenbone-nvt-sync: Another process related to the feed update is already running.
```

any ideas?
