### ISSUE TITLE
postfix log files

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#2]
Hi,

First thing to say, thank you for providing an up2date version of OpenVAS!
Question: My mail alerts aren't working, probably caused by some security settings of my mail server. Is it possible to get the mail logs from Postfix? I can't find anything inside the container since syslog isn't available. Logging to a file seems possible with Postfix >3.4 but included is a 3.3 version...
any ideas?

**Comment by immauss** [comment]
Well ... you could install syslog. (probably rsyslog)
The image is fully functioning Ubuntu. So the following should get you there:
apt update 
apt install syslog-ng 
service syslog-ng start
service postfix restart

You should now have a mail.log in /var/log 

And as I test this .... I realize that mail is no longer working from on the latest build 
..... 
Tested all of the scanning functionality, but didn't test the mail. 

 So there may be another underlying issue.  I'll put some energy on this a little later today and get back to you. 

Thanks,
Scott

**Comment by immauss** [comment]
OK ... for my case, it was a problem with the mail server on the host, and not related to the container.  If you are using the docker host as the relay host, make sure you add appropriate iptables rules to the host so the container can connect.

**Comment by immauss** [comment]
And if you have to modify anything inside the container to get it working, please let me know and I'll if I can work it into the build. Otherwise, you'll have to make those changes again when you pull a new image at the next release.

Thanks,
Scott

**Comment by cybermcm** [comment]
Thank you for your fast answer... no clue why I didn't think about installing syslog ;-)...
Anyway, installed syslog -> mail is working
Removed container, tried again -> mail is not working...
is it possible that syslog is required? can you confirm this behavior?

**Comment by immauss** [comment]
Sorry for the delay this time. 
I can confirm that my setup is working and sending mail **without** installing syslog.

**Comment by cybermcm** [comment]
thx for your reply...
I tested it again, removed container, removed image, started fresh -> mail not working (created a test alert on task creation)
jumped into the container -> "service postfix restart" and suddenly mails get delivered (even the "old" one after container creation, so they seem to be stucked in a queue and postfix restart triggers them...
any idea what the problem could be in this case?

**Comment by immauss** [comment]
Can you send me the command you are using to start the container? Are you sending the email to the same host the container is running on or anther mail server ?

-Scott

G.E. Scott Knauss
i <mailto:scott@knauss.com>mmauss@gmail.com
Computer Geek 
Security Guy
Linux Guru

**Comment by cybermcm** [comment]
I  did a little more digging, it is a DNS issue. Right after a fresh start the folder
/var/spool/postfix/etc/ is empty resulting in a DNS error.
I looked for my queued test mail and the error message is
```
Host or domain name not found. Name service error for name=mail type=MX: Host not found, try again
```
right after a 
> service postfix restart

the folder /var/spool/postfix/etc/ is filled with files and it contains a resolv.conf copy and DNS starts working...

not sure why this happens with my container. My mail server is another docker container on the same host.

docker compose:
```
openvas:
  container_name: openvas
  environment:
   - PASSWORD=${openvas_OV_PASSWORD}
   - RELAYHOST=mail
  hostname: openvas.${hostname}
  image: immauss/openvas
  labels:
   - ${ouro_true}
   - traefik.enable=true
   - "traefik.http.routers.openvas.rule=Host(`openvas.${hostname}`)"
   - traefik.http.routers.openvas.entrypoints=web-secure
   - traefik.http.routers.openvas.tls.certresolver=le
   - traefik.http.routers.openvas.tls=true
   - traefik.http.routers.openvas.priority=2
   - traefik.http.routers.openvas.tls.options=default
   - traefik.http.routers.openvas.service=openvas
   - traefik.http.services.openvas.loadbalancer.server.port=9392
  networks:
   - web
  restart: always
  volumes:
   - ${timezone}
   - ${localtime}
   - /opt/openvas:/data
```
