### ISSUE TITLE
[BUG] Healthchecks report no issue but container remains unhealthy 

### ISSUE THREAD

**Issue by mnaismith** [immauss/openvas#234]
I've been running your excellent Openvas container for some time.  This week I have the below issue. 

I am running Ubuntu 22.04.3 with all system updates applied. 

I pull down latest immauss/openvas image. 

I run with command 
 
docker run --detach --publish 127.0.0.1:8080:9392 --publish 127.0.0.1:9390:9390 -e SKIPSYNC=true -e PASSWORD="blabla" --volume openvas:/data --name openvas immauss/openvas

I watch the status of the container and it never becomes healthy. 

CONTAINER ID   IMAGE             COMMAND               CREATED          STATUS                      PORTS                                                NAMES
c0691e402070   immauss/openvas   "/scripts/start.sh"   23 minutes ago   Up 23 minutes (unhealthy)   127.0.0.1:9390->9390/tcp, 127.0.0.1:8080->9392/tcp   openvas

Logs attached. 

[logfile.txt](https://github.com/immauss/openvas/files/13407316/logfile.txt)

**Comment by immauss** [comment]
That is strange. The logs look perfectly normal and the output from the health check script shows no issues.  I'll do some testing here and see if I can replicate. 

And thanks for the subscription! Much appreciated. 

-Scott

**Comment by immauss** [comment]
I've done several rounds of testing with this, and I'm not able to reproduce it.
Is the running container useable despite the unhealthy indication? 

Have you tried restarting docker? 

The really odd part is that the logs show the script is completing successfully.  If that happens, then it should show as healthy on a "docker ps" (after 5 minutes). I've been staring at the healthcheck.sh trying to think of some scenario that would make it exit with something other than 0 and still give the "all good" message, but I'm coming up empty. 

Can you send me the out from the following:
```
docker exec -it openvas bash -x "/scripts/healthcheck.sh"
```

If the healthcheck.sh is doing something funky, this should help me find it. 

Thanks,
Scott

**Comment by grandaor** [comment]
I've the same thing:

```
$ docker exec -it openvas bash -x "/scripts/healthcheck.sh"
++ cat /usr/local/etc/running-as
+ FUNC=single
++ df -h /
++ tr -d %
++ awk '/overlay/{ if ( $5 > 95 ) print $4}'
+ HIGHROOT=
++ df /
++ tr -d %
++ awk '/overlay/{print $4}'
+ ROOTSPC=32287300
+ '[' -z ']'
++ df -h
++ tr -d %
++ awk '/data/{ if ( $5 > 95 ) print $4}'
+ HIGHDATA=
++ df
++ tr -d %
++ awk '/data/{print $4}'
+ DATASPC=32287300
+ '[' -z ']'
+ case $FUNC in
+ FAIL=0
++ su -c 'gvmd --get-scanners' gvm
++ awk '/OpenVAS/{print  $1}'
+ UUID=08b69003-5fc2-4037-a479-93b440211c73
+ su -c 'gvmd --verify-scanner=08b69003-5fc2-4037-a479-93b440211c73' gvm
+ grep OpenVAS
Scanner version: OpenVAS 22.7.7.
+ '[' 0 -eq 1 ']'
+ nmap -p 9390 localhost
+ grep -qs '9390.*open'
+ '[' 0 -eq 2 ']'
+ curl -f http://localhost:9392/
<!doctype html><html><head><link rel="icon" href="/img/favicon.png" type="image/png"/><title>Greenbone Security Assistant</title><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><script type="text/javascript" src="/config.js"></script><script defer="defer" src="/static/js/main.5e6dfc4c.js"></script><link href="/static/css/main.d6631c26.css" rel="stylesheet"></head><body><div id="app"></div><div id="portals"></div></body></html>+ '[' 0 -eq 3 ']'
+ redis-cli -s /run/redis/redis.sock ping
PONG
+ '[' 0 -eq 4 ']'
+ nmap -p 5432 localhost
+ grep -qs '5432.*open'
+ '[' 0 -eq 5 ']'
+ '[' 0 -ne 0 ']'
+ echo ' Healthchecks completed with no issues.'
```

I've just pull the latest image and still unhealthy.

I've test with a clean volume and still unhealthy.

```
$ docker ps
CONTAINER ID   IMAGE                                     COMMAND                  CREATED          STATUS                      PORTS                                                          NAMES
036c99b9142b   immauss/openvas                           "/scripts/start.sh"      15 minutes ago   Up 15 minutes (unhealthy)                                                                  openvas
```

**Comment by immauss** [comment]
@grandaor Are you able to login and use the container despite the "unhealthy" status? 

Thanks,
Scott

**Comment by immauss** [comment]
@mnaismith Are you also using traefik ?

**Comment by immauss** [comment]
@grandaor 
Can you walk me through how you have traefik setup?  I've never really used it. If you can help me replicate your setup, maybe I can find the issue. 

Thanks,
Scott

**Comment by grandaor** [comment]
I don't think this issue is related to traefik because without it, the dock openvas is still unhealthy...

my traefik setup :

```
version: '3.3'
services:
  traefik:
    image: traefik:latest
    env_file:
    - .env
    container_name: traefik
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.middlewares=https-redirect
      - traefik.http.routers.traefik-public-https.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-public-https.entrypoints=https
      - traefik.http.routers.traefik-public-https.tls=true
      - traefik.http.routers.traefik-public-https.service=api@internal
      - traefik.http.routers.traefik-public-https.tls.certresolver=le
      - traefik.http.routers.traefik-public-https.middlewares=admin-auth
      - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certificates:/certificates
      - /var/log/traefik/:/logs/
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --accesslog.filePath=/logs/access.log
      - --api
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
```

my openvas setup :

```
version: '3.3'

services:

  openvas:
    image: immauss/openvas
    container_name: openvas
    env_file:
      - .env
    restart: unless-stopped
    environment:
      PASSWORD: ${PASSWORD?Variable not set}
      HTTPS: false
      PUBLIC_HOSTNAME: ${URL_T?Variable not set}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.openvas-http.rule=Host("${URL_T?Variable not set}")
      - traefik.http.routers.openvas-http.entrypoints=http
      - traefik.http.routers.openvas-http.middlewares=https-redirect
      - traefik.http.routers.openvas-https.rule=Host("${URL_T?Variable not set}")
      - traefik.http.routers.openvas-https.entrypoints=https
      - traefik.http.routers.openvas-https.tls=true
      - traefik.http.routers.openvas-https.tls.certresolver=le
      - traefik.http.middlewares.hsts-headers.headers.stsSeconds=315360000
      - traefik.http.middlewares.hsts-headers.headers.stsPreload=true
      - traefik.http.middlewares.hsts-headers.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.hsts-headers.headers.customFrameOptionsValue=SAMEORIGIN
      - traefik.http.middlewares.hsts-headers.headers.sslRedirect=true
      - traefik.http.middlewares.hsts-headers.headers.forceSTSHeader=true
      - traefik.http.middlewares.hsts-headers.headers.referrerPolicy=same-origin
      - traefik.http.routers.openvas-https.middlewares=hsts-headers
      - traefik.http.services.openvas.loadbalancer.server.port=9392
networks:
  traefik-public:
    external: true
    driver: overlay
```
