### ISSUE TITLE
issues with 20.08.05

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#25]
Tried your new docker container 20.08.05, having issues:

1) log file:
endless repeating of
```
today at 8:26 AM  md manage:   INFO:2021-02-08 07h26.25 utc:31631: update_scap: Updating data from feed
today at 8:26 AM  md manage:WARNING:2021-02-08 07h26.25 utc:31631: update_scap_cpes: No CPE dictionary found at /usr/local/var/lib/gvm/scap-data/official-cpe-dictionary_v2.2.xml
today at 8:26 AM  md manage:WARNING:2021-02-08 07h26.35 utc:31640: update_scap: No SCAP db present, rebuilding SCAP db from scratch
today at 8:26 AM  md manage:   INFO:2021-02-08 07h26.35 utc:31640: update_scap: Updating data from feed
```
I tried from scratch and with https://github.com/immauss/gvm-var-lib, didn't help

2) another thing and more important:
Scan config and port list are empty, it is not possible to add a scan config in the GUI, error:
```
Failed to find config 'daba56c8-73ec-11df-a475-002264764cea'
```

Is there something on my side that I'm doing wrong?
My compose file:
```
openvas:
  container_name: openvas
  environment:
   - PASSWORD=xyz
   - HTTPS=false
   - RELAYHOST=mail.zzz
   - SKIPSYNC=true
  hostname: openvas.zzz
  image: immauss/openvas:20.08.05
  labels:
   - com.centurylinklabs.watchtower.enable=true
  ports:
   - 8083:9392
  restart: always
  volumes:
   - /opt/docker/openvas:/data
```

BTW: Thanks for your work!
