### ISSUE TITLE
startup error with 22.4.44 and latest image

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#270]
**Describe the bug**
Openvas won't start with image 22.4.44 or latest (amd64)

**To Reproduce**
   - docker-compose.yml
```
openvas:
  container_name: openvas
  cpus: 4
  environment:
   - PASSWORD=${openvas_OV_PASSWORD}
   - RELAYHOST=${EMAIL_HOST} # immauss/openvas
   - SMTPPORT=25 # immauss/openvas
   - QUIET=true # immauss/openvas
   #- SKIPSYNC=true # immauss/openvas, faster startup without it
  hostname: openvas
  image: immauss/openvas:22.4.44
  networks:
   - web
  restart: unless-stopped
  volumes:
   - ${TIMEZONE}
   - ${LOCALTIME}
   - ${BACKUP_PATH} # for backup
   - /_openvas:/data # immauss/openvas
```

2. When did the issue occur? 
  - the container failed to start? yes

**Expected behavior**
clean startup

**Environment (please complete the following information):**
 - OS: Debian 12.5
 - Memory available to OS:  [ 18G ]
 - Container environment used with version: [ Docker version 26.1.1 ]

**logs**
[openvas.log](https://github.com/immauss/openvas/files/15209724/openvas.log)

**Additional context**
reverting to 22.4.43 -> working
