### ISSUE TITLE
rsync: failed to connect to feed.community.greenbone.net 

### ISSUE THREAD

**Issue by MrMarioMichel** [immauss/openvas#39]
Hi ! 

I do have issues with the latest image.

compose file

```
version: "3.3"
services:
  openvas:
    ports:
      - "808:9392"
    environment:
      - "PASSWORD=paswd"
    dns:
      - 1.1.1.1
    volumes:
      - "openvas:/data"
    container_name: openvas
    image: immauss/openvas:latest
volumes:
  openvas:
```

log

```
penvas    | Unpacking base feeds data from /usr/lib/var-lib.tar.xz
openvas    | Migrating the database to the latest version if needed.
openvas    | Updating NVTs and other data
openvas    | This could take a while if you are not using persistent storage for your NVTs
openvas    |  or this is the first time pulling to your persistent storage.
openvas    |  the time will be mostly dependent on your available bandwidth.
openvas    |  We sleep for 5 seconds between sync command to make sure everything closes
openvas    |  and it doesnt' look like we are connecting more than once.
openvas    |  Pulling NVTs from greenbone
openvas    | <28>May  5 15:29:11 greenbone-nvt-sync: The log facility is not working as expected. All messages will be written to the standard error stream.
openvas    | <29>May  5 15:29:11 greenbone-nvt-sync: No Greenbone Security Feed access key found, falling back to Greenbone Community Feed
openvas    | <29>May  5 15:29:16 greenbone-nvt-sync: Configured NVT rsync feed: rsync://feed.community.greenbone.net:/nvt-feed
openvas    | rsync: failed to connect to feed.community.greenbone.net (45.135.106.142): Connection timed out (110)
openvas    | rsync: failed to connect to feed.community.greenbone.net (2a0e:6b40:20:106:20c:29ff:fe67:cbb5): Network is unreachable (101)
openvas    | rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
openvas    | <27>May  5 15:31:24 greenbone-nvt-sync: rsync failed.
openvas    |  Pulling scapdata from greenbone
openvas    | rsync: failed to connect to feed.community.greenbone.net (45.135.106.142): Connection timed out (110)
openvas    | rsync: failed to connect to feed.community.greenbone.net (2a0e:6b40:20:106:20c:29ff:fe67:cbb5): Network is unreachable (101)
openvas    | rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]
openvas exited with code 1

````

tried also to give it a public DNS but it was anyways resolved but nothing retrieved
