### ISSUE TITLE
using latest amd64 image -> warnings and no reports

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#44]
Using latest amd64  tag from docker hub with a  clean data path (from scratch)
`sha256:34cc22d839eb28798681285a25c2eb0f1b7c955779c8c0154c7fd68a97a52454`

```
openvas:
  container_name: openvas
  cpus: 4
  environment:
   - PASSWORD=${openvas_OV_PASSWORD}
   - RELAYHOST=${EMAIL_HOST} # immauss/openvas, securecompliance/gvm
   - SMTPPORT=25 # immauss/openvas, securecompliance/gvm
   - QUIET=true # immauss/openvas
   - SKIPSYNC=true
  hostname: openvas.${HOSTNAME}
  image: immauss/openvas
  labels:
   - ${WATCHTOWER_TRUE}
   - diun.enable=true
   - diun.watch_repo=true
   - traefik.enable=true
   - "traefik.http.routers.openvas.rule=Host(`openvas.${HOSTNAME}`)"
   - traefik.http.routers.openvas.entrypoints=web-secure
   - traefik.http.routers.openvas.tls.certresolver=le
   - traefik.http.routers.openvas.tls=true
   - traefik.http.routers.openvas.priority=2
   - traefik.http.routers.openvas.tls.options=default
   - traefik.http.routers.openvas.service=openvas
   - traefik.http.services.openvas.loadbalancer.server.port=9392
  networks:
   - web
  restart: always
  volumes:
   - ${DOCKER_PATH}/openvas:/data # immauss/openvas, securecompliance/gvm
```

1) seeing a WARNING message every 10 seconds:
`md manage:WARNING:2021-05-31 20h21.33 utc:32750: secinfo_feed_version_status: last scap database update later than last feed update`

2) pdf report not working, download ends with a 0 byte file (correct file name but no content); doesn't work as email report
