### ISSUE TITLE
current latest image amd64 won't start

### ISSUE THREAD

**Issue by cybermcm** [immauss/openvas#83]
Something is broken with latest image (amd64, 8885aef712c6). Container won't start at all, no log entry.
using tag 21.4.4-03 -> working

**Comment by immauss** [comment]
Are you using bind mounts or docker managed volumes ?

**Comment by cybermcm** [comment]
sorry, should have posted my compose, bind mounts:
```
openvas:
  container_name: openvas
  cpus: 4
  environment:
   - PASSWORD=${openvas_OV_PASSWORD}
   - QUIET=true # immauss/openvas
   - SKIPSYNC=true
  hostname: openvas
  image: immauss/openvas
  labels:
   - ${WATCHTOWER_TRUE}
   - diun.enable=true
   - diun.watch_repo=true
   - traefik.enable=true
   - "traefik.http.routers.openvas.rule=Host(`openvas.${HOSTNAME}`)"
   - traefik.http.routers.openvas.entrypoints=web-secure
   - traefik.http.routers.openvas.tls.certresolver=le
   - traefik.http.routers.openvas.tls=true
   - traefik.http.routers.openvas.priority=2
   - traefik.http.routers.openvas.tls.options=default
   - traefik.http.routers.openvas.service=openvas
   - traefik.http.services.openvas.loadbalancer.server.port=9392
  networks:
   - web
  restart: always
  volumes:
   - /_openvas:/data # immauss/openvas
```
